#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------


if [ ! -f /data/minecraft_server.jar ]
then
    # download the v 1.16 server.jar as per https://www.minecraft.net/en-us/download/server/
    # https://launcher.mojang.com/v1/objects/a412fd69db1f81db3f511c1463fd304675244077/server.jar
    curl "https://launcher.mojang.com/v1/objects/a412fd69db1f81db3f511c1463fd304675244077/server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data; java -Xmx2G -jar minecraft_server.jar nogui

