#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------


if [ ! -f /data/minecraft_server.jar ]
then
    # download the v 1.15.2 server.jar as per https://www.minecraft.net/en-us/download/server/
    curl "https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx2G -jar minecraft_server.jar nogui

